// Copyright 2026 Inspyr Studio, SAS. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Factories/Factory.h"
#include "EditorReimportHandler.h"
#include "UCygonUsdaFactory.generated.h"

class UAssetImportData;
class UPackage;

/// Custom factory responsible for importing and handling `.usda` files generated by Cygon.
/// It acts as a bridge with Unreal Engine's native USD Importer, while applying custom logic
/// (such as filtering out partial sub-mesh files) to ensure a clean import and seamless hot-reloading.
UCLASS()
class UCygonUsdaFactory : public UFactory, public FReimportHandler
{
	
	GENERATED_BODY()
public:
	UCygonUsdaFactory();

	// #==================================================#
	// # Import
	// #==================================================#
	
	/// Determines if this factory can import a specific file
	/// @param Filename The full path to the file being evaluated for import
	/// @return true if the file is a .usda file exported from Cygon, false otherwise
	virtual bool FactoryCanImport(const FString& Filename) override;
	virtual UObject* FactoryCreateFile(UClass* InClass, UObject* InParent, FName InName, EObjectFlags Flags, const FString& Filename, const TCHAR* Parms, FFeedbackContext* Warn, bool& bOutCanceled) override;
	
	// #==================================================#
	// # Reimport
	// #==================================================#
	
	/// Determines if this factory can handle the reimporting of a specific object
	/// @param Obj The object to evaluate for reimport
	/// @param OutFilenames An array that will be populated with the source filenames associated with the object
	/// @return true if the object is tied to a Cygon .usda file and can be reimported, false otherwise
	virtual bool CanReimport(UObject* Obj, TArray<FString>& OutFilenames) override;
	virtual void SetReimportPaths(UObject* Obj, const TArray<FString>& NewReimportPaths) override;
	virtual EReimportResult::Type Reimport(UObject* Obj) override;

	/// Get the factory priority to ensure it is chosen over the default USD importer for files that match our criteria
	/// @return The priority value for this factory (DefaultImportPriority + 1)
	virtual int32 GetPriority() const override { return DefaultImportPriority + 1; }

	/// Check if the file contains the "Cygon" tag in its first line to identify it as a file meant to be imported via our custom Factory
	/// @param Filename The file path to check
	/// @return true if the file contains the "Cygon" tag in its first line, false otherwise
	static bool IsCygonFile(const FString& Filename);

	/// Check if the file is a referenced sub-mesh (lives in a `meshes/` folder) rather than a full scene
	/// @param Filename The file path to check
	/// @return true if the file is a sub-mesh, false otherwise
	static bool IsSimpleMesh(const FString& Filename);

	/// @return true while a Play-In-Editor session is running. Imports triggered during play must not
	/// write to disk; the save is deferred until PIE ends (see FinalizeImportedMeshCollision).
	static bool IsPlayInEditorActive();

private:
	/// Retrieve the AssetImportData of the given object, whether it exposes one as a reflected property
	/// or only through a typed accessor
	/// @param Obj The object to inspect
	/// @return The object's AssetImportData, or nullptr when it has none
	static UAssetImportData* FindAssetImportData(UObject* Obj);
	
	/// Retrieve the source filename from the AssetImportData of the given object, if it exists
	/// @param Obj The object to retrieve the source filename from
	/// @return The source filename if it exists, an empty string otherwise
	FString GetSourceFilename(UObject* Obj) const;
	
	/// Resolve where a scene's assets belong from the scene file's own location on disk.
	/// Deriving it from an already imported asset's package path instead is what used to write assets into
	/// the engine installation: the reimport manager can hand us a transient duplicate such as
	/// `MI_Cobblestone_Tessellated_1`, whose package path is `/Engine/Transient.MI_Cobblestone_Tessellated_1`,
	/// and `FPaths::GetPath` of that is `/Engine`. Cygon scenes always live under the project's Content
	/// folder, so the file's own path is both exact and impossible to escape from.
	/// @param SourceFilename Absolute path of the `.usda` scene
	/// @param OutDestinationPath Receives the long package path to import into, e.g. `/Game/Test/TOM`
	/// @return true if the scene lives somewhere we are willing to write assets to
	static bool ResolveDestinationPath(const FString& SourceFilename, FString& OutDestinationPath);
	
	/// Whether a scene in its current on-disk state has already been imported during this editor session.
	/// One stage import refreshes every asset the scene produces, but each of those assets records the
	/// scene as its own source file, so the reimport manager queues a full stage import *per asset*. A
	/// scene exporting 885 component prims yields ~837 static meshes, i.e. ~837 full imports of the whole
	/// scene, each allocating hundreds of packages that stay resident: the editor pegs a core and climbs
	/// until it runs out of memory. This collapses that cascade to a single import.
	/// @param SourceFilename Absolute path of the `.usda` scene
	/// @return true when the file is unchanged since we last imported it, so the work can be skipped
	static bool IsSceneAlreadyImported(const FString& SourceFilename);
	
	/// Record the on-disk state of a scene we just imported, for IsSceneAlreadyImported to compare against.
	/// @param SourceFilename Absolute path of the `.usda` scene
	static void MarkSceneImported(const FString& SourceFilename);
	
	/// Creates an import task for a USD file
	/// @param Filename The source file path of the asset to import
	/// @param DestinationPath The destination path in the content browser
	/// @return The newly created and configured asset import task
	UAssetImportTask* CreateImportTask(const FString& Filename, const FString& DestinationPath);
	
	/// Pin every option of the native USD importer to a fixed value.
	/// UUsdStageImportOptions is declared `config = EditorPerProjectUserSettings` with virtually every
	/// property marked `config`, so a freshly constructed options object is seeded from
	/// `%LOCALAPPDATA%/UnrealEngine/<version>/Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini`.
	/// That file is per-user, per-machine and never in source control: whatever an artist last picked in
	/// the editor's own USD import dialog would otherwise become this plugin's import settings, which is
	/// why an identical scene could import differently from one workstation to the next.
	/// @param ImportOptions The UUsdStageImportOptions instance to pin, accessed through reflection to
	///        avoid a hard dependency on the USDStageImporter module
	static void ApplyDeterministicImportOptions(UObject* ImportOptions);
	
	/// Set every imported static mesh to use its render geometry as simple collision
	/// (CTF_UseComplexAsSimple) and resave it. The native USD importer cooks complex collision
	/// but no simple collision, so gameplay queries would otherwise pass straight through the mesh.
	/// @param ImportedObjects The objects produced by the import task; non static-mesh objects are ignored
	void ApplyComplexAsSimpleCollision(const TArray<UObject*>& ImportedObjects) const;

	/// Apply complex-as-simple collision to the given meshes and resave them. Scheduled by
	/// ApplyComplexAsSimpleCollision to run on the next editor tick.
	/// @param Meshes References to the imported static meshes.
	static void FinalizeImportedMeshCollision(const TArray<TWeakObjectPtr<UStaticMesh>>& Meshes);

	/// Saves the packages whose collision was hot-reloaded during a Play-In-Editor session (we never
	/// write to disk mid-play). Bound to FEditorDelegates::EndPIE on demand, and unbound after it runs.
	static void SavePiePendingPackages(bool bIsSimulating);

	/// Mesh packages dirtied by a collision pass that ran during PIE, awaiting save when PIE ends.
	static TSet<TWeakObjectPtr<UPackage>> PiePendingSavePackages;

	/// Handle for the one-shot EndPIE save callback; valid only while a deferred save is pending.
	static FDelegateHandle PieEndSaveHandle;

	/// Re-entrancy guard: true while we drive a reimport through the native USD importer, so the
	/// reimport our own ImportAssetTasks call may trigger is ignored (prevents an infinite loop).
	static bool bIsHandlingProxyCygonReimport;
	
	/// On-disk state ("size|timestamp") of the scenes imported so far this session, keyed by the scene's
	/// absolute path in lower case. Backs IsSceneAlreadyImported.
	static TMap<FString, FString> ImportedSceneSignatures;
};
