// Copyright Inspyr Studio, SAS. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Factories/Factory.h"
#include "EditorReimportHandler.h"
#include "UCygonUsdaFactory.generated.h"

/// Custom factory responsible for importing and handling `.usda` files generated by Cygon.
/// It acts as a bridge with Unreal Engine's native USD Importer, while applying custom logic
/// (such as filtering out partial sub-mesh files) to ensure a clean import and seamless hot-reloading.
UCLASS()
class UCygonUsdaFactory : public UFactory, public FReimportHandler
{
	
	GENERATED_BODY()
public:
	UCygonUsdaFactory();

	// #==================================================#
	// # Import
	// #==================================================#
	
	/// Determines if this factory can import a specific file
	/// @param Filename The full path to the file being evaluated for import
	/// @return true if the file is a .usda file exported from Cygon, false otherwise
	virtual bool FactoryCanImport(const FString& Filename) override;
	virtual UObject* FactoryCreateFile(UClass* InClass, UObject* InParent, FName InName, EObjectFlags Flags, const FString& Filename, const TCHAR* Parms, FFeedbackContext* Warn, bool& bOutCanceled) override;
	
	// #==================================================#
	// # Reimport
	// #==================================================#
	
	/// Determines if this factory can handle the reimporting of a specific object
	/// @param Obj The object to evaluate for reimport
	/// @param OutFilenames An array that will be populated with the source filenames associated with the object
	/// @return true if the object is tied to a Cygon .usda file and can be reimported, false otherwise
	virtual bool CanReimport(UObject* Obj, TArray<FString>& OutFilenames) override;
	virtual void SetReimportPaths(UObject* Obj, const TArray<FString>& NewReimportPaths) override;
	virtual EReimportResult::Type Reimport(UObject* Obj) override;

	/// Get the factory priority to ensure it is chosen over the default USD importer for files that match our criteria
	/// @return The priority value for this factory (DefaultImportPriority + 1)
	virtual int32 GetPriority() const override { return DefaultImportPriority + 1; }

	/// Check if the file contains the "Cygon" tag in its first line to identify it as a file meant to be imported via our custom Factory
	/// @param Filename The file path to check
	/// @return true if the file contains the "Cygon" tag in its first line, false otherwise
	static bool IsCygonFile(const FString& Filename);

	/// Check if the file is a referenced sub-mesh (lives in a `meshes/` folder) rather than a full scene
	/// @param Filename The file path to check
	/// @return true if the file is a sub-mesh, false otherwise
	static bool IsSimpleMesh(const FString& Filename);

private:
	/// Retrieve the source filename from the AssetImportData of the given object, if it exists
	/// @param Obj The object to retrieve the source filename from
	/// @return The source filename if it exists, an empty string otherwise
	FString GetSourceFilename(UObject* Obj) const;
	
	/// Creates an import task for a USD file
	/// @param Filename The source file path of the asset to import
	/// @param DestinationPath The destination path in the content browser
	/// @return The newly created and configured asset import task
	UAssetImportTask* CreateImportTask(const FString& Filename, const FString& DestinationPath);
	
	/// Set every imported static mesh to use its render geometry as simple collision
	/// (CTF_UseComplexAsSimple) and resave it. The native USD importer cooks complex collision
	/// but no simple collision, so gameplay queries would otherwise pass straight through the mesh.
	/// @param ImportedObjects The objects produced by the import task; non static-mesh objects are ignored
	void ApplyComplexAsSimpleCollision(const TArray<UObject*>& ImportedObjects) const;
};
